# Generated by Django 2.0.4 on 2018-04-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_desc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
